### ISSUE TITLE
Pontential danger with update and delete operations

### ISSUE THREAD

**Issue by ghost** [get-net/data-mapper#12]
For example, I want to update a record with id = 1 and set a value of some_field to 'some_value':

```lua
-- some module containing data-mapper models
local dm = require("models")

dm.some_table:update({some_field = 'some_value'}, {id = 1})
```

The function call runs a query to the database that looks like this:
```sql
UPDATE some_table SET some_field='some_value' WHERE id=1;
```

It's all fine and dandy until the **id** value for some reason contains nil, then the query becomes something like this,
due to the peculiarities of the lua language:
```sql
UPDATE some_table SET some_field='some_value';
```

Which leads to potential danger of updating all of the values in the table with a single query.

**Comment by norguhtar** [comment]
Add force flag and checks for disable massive update select delete
