### ISSUE TITLE
calling build_sql overwrites the result of previous call

### ISSUE THREAD

**Issue by arsenitem** [get-net/data-mapper#9]
For example i create first query
local sql = token:select():join(client):where(
       cond:_and(
               { token, access = access },
               cond:_or(
                       { tscreate = "now() - (expires_in || ' sec')::INTERVAL", ">=" },
                       {token, expires_in = -1 }),
               { client, status = true }
       ))
Then i create another query
local sql2 = token:select():join(client):where(
    cond:_and(
            { token, access = access }
    ))

Instead of getting the result of sql.build_query() i get sql2.build_query execution result

print(string.format("SQL:[%s]", sql:build_sql()))
print(string.format("SQL:[%s]", sql2:build_sql()))

SQL:[SELECT ot.tscreate AS ot_tscreate, ot.uid_service AS ot_service, ot.expires_in AS ot_expires_in, ot.code AS ot_code, ot.uid_client AS ot_client, ot.uid_agent AS ot_agent, ot.access AS ot_access, ot.uid AS ot_uid, ot.refresh AS ot_refresh, oc.client_redirect_uri AS oc_client_redirect_uri, oc.name AS oc_name, oc.status AS oc_status, oc.uid AS oc_uid, oc.secret AS oc_secret FROM oauth.token AS ot  JOIN oauth.client AS oc ON oc.uid = ot.uid_client WHERE (ot.access = '3009c18bf5090cbf4ecada5d349cb6d6ebda124445a1d5dd005e50b9c344be01')]

SQL:[SELECT ot.tscreate AS ot_tscreate, ot.uid_service AS ot_service, ot.expires_in AS ot_expires_in, ot.code AS ot_code, ot.uid_client AS ot_client, ot.uid_agent AS ot_agent, ot.access AS ot_access, ot.uid AS ot_uid, ot.refresh AS ot_refresh, oc.client_redirect_uri AS oc_client_redirect_uri, oc.name AS oc_name, oc.status AS oc_status, oc.uid AS oc_uid, oc.secret AS oc_secret FROM oauth.token AS ot  JOIN oauth.client AS oc ON oc.uid = ot.uid_client WHERE (ot.access = '3009c18bf5090cbf4ecada5d349cb6d6ebda124445a1d5dd005e50b9c344be01')]

**Comment by norguhtar** [comment]
As happened. 

> token:select():join(client):where(
cond:_and(
{ token, access = access }
))

this query just change sql set in token.If you need sql for first and second query you shold 

```lua
local sql = token:select():join(client):where(
cond:_and(
{ token, access = access },
cond:_or(
{ tscreate = "now() - (expires_in || ' sec')::INTERVAL", ">=" },
{token, expires_in = -1 }),
{ client, status = true }
)):build_sql()
local sql2 = token:select():join(client):where(
cond:_and(
{ token, access = access }
)):build_sql()
```
And use this
